// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAlpeSxcDD-OVz1jzKbmYY4-2ac2IKYw8',
    appId: '1:76938604893:web:58f4be5ede37a79d4378b4',
    messagingSenderId: '76938604893',
    projectId: 'nak-tumpang',
    authDomain: 'nak-tumpang.firebaseapp.com',
    storageBucket: 'nak-tumpang.firebasestorage.app',
    measurementId: 'G-4GK67VCBZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD89AZo-l51YTLLyKZZq7HRLn5gU4EUScY',
    appId: '1:76938604893:android:061131af3d41edac4378b4',
    messagingSenderId: '76938604893',
    projectId: 'nak-tumpang',
    storageBucket: 'nak-tumpang.firebasestorage.app',
  );
}
